In [1]:
import pandas as pd
#pyformat.info megnézni

In [2]:
df = pd.read_csv('movie_metadata.csv', sep=',')

In [3]:
df.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...   
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...   
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...   
3                 27000.0  448130642.0                  Action|Thriller  ...   
4                   131.0          NaN                      Documentary  ...   

  num_user_for_reviews language  country  content_rating       budget  \
0               3054.0  English      USA           PG-13  237000000.0   
1               1238.0  English      USA           PG-13  300000000.0   
2                994.0  English       UK           PG-13  245000000.0   
3               2701.0  English      USA           PG-13  250000000.0   
4                  NaN      NaN      NaN             NaN          NaN   

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78   
1      2007.0                 5000.0        7.1          2.35   
2      2015.0                  393.0        6.8          2.35   
3      2012.0                23000.0        8.5          2.35   
4         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

In [4]:
pd.set_option('max_columns', None)

In [5]:
df.tail()

color     director_name  num_critic_for_reviews  duration  \
5038  Color       Scott Smith                     1.0      87.0   
5039  Color               NaN                    43.0      43.0   
5040  Color  Benjamin Roberds                    13.0      76.0   
5041  Color       Daniel Hsia                    14.0     100.0   
5042  Color          Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
5038                      2.0                   318.0     Daphne Zuniga   
5039                      NaN                   319.0     Valorie Curry   
5040                      0.0                     0.0     Maxwell Moody   
5041                      0.0                   489.0     Daniel Henney   
5042                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes    gross                        genres  \
5038                   637.0      NaN                  Comedy|Drama   
5039                   841.0      NaN  Crime|Drama|Mystery|Thriller   
5040                     0.0      NaN         Drama|Horror|Thriller   
5041                   946.0  10443.0          Comedy|Drama|Romance   
5042                    86.0  85222.0                   Documentary   

     actor_1_name                 movie_title  num_voted_users  \
5038  Eric Mabius    Signed Sealed Delivered               629   
5039  Natalie Zea  The Following                         73839   
5040  Eva Boehnke       A Plague So Pleasant                38   
5041    Alan Ruck           Shanghai Calling              1255   
5042  John August          My Date with Drew              4285   

      cast_total_facebook_likes    actor_3_name  facenumber_in_poster  \
5038                       2283    Crystal Lowe                   2.0   
5039                       1753   Sam Underwood                   1.0   
5040                          0  David Chandler                   0.0   
5041                       2386     Eliza Coupe                   5.0   
5042                        163        Jon Gunn                   0.0   

                                          plot_keywords  \
5038             fraud|postal worker|prison|theft|trial   
5039       cult|fbi|hideout|prison escape|serial killer   
5040                                                NaN   
5041                                                NaN   
5042  actress name in title|crush|date|four word tit...   

                                        movie_imdb_link  num_user_for_reviews  \
5038  http://www.imdb.com/title/tt3000844/?ref_=fn_t...                   6.0   
5039  http://www.imdb.com/title/tt2071645/?ref_=fn_t...                 359.0   
5040  http://www.imdb.com/title/tt2107644/?ref_=fn_t...                   3.0   
5041  http://www.imdb.com/title/tt2070597/?ref_=fn_t...                   9.0   
5042  http://www.imdb.com/title/tt0378407/?ref_=fn_t...                  84.0   

     language country content_rating  budget  title_year  \
5038  English  Canada            NaN     NaN      2013.0   
5039  English     USA          TV-14     NaN         NaN   
5040  English     USA            NaN  1400.0      2013.0   
5041  English     USA          PG-13     NaN      2012.0   
5042  English     USA             PG  1100.0      2004.0   

      actor_2_facebook_likes  imdb_score  aspect_ratio  movie_facebook_likes  
5038                   470.0         7.7           NaN                    84  
5039                   593.0         7.5         16.00                 32000  
5040                     0.0         6.3           NaN                    16  
5041                   719.0         6.3          2.35                   660  
5042                    23.0         6.6          1.85                   456

In [6]:
print("%d (sorok amiben van NaN) / %d (összes)"%(len(df[df.isnull().any(axis=1)]), len(df)))
#sorok számolása aminek bármely oszlopában van NaN

1287 (sorok amiben van NaN) / 5043 (összes)


In [7]:
df = df[~df.isnull().any(axis=1)]

In [8]:
df.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
5  Color     Andrew Stanton                   462.0     132.0   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
5                    475.0                   530.0   Samantha Morton   

   actor_1_facebook_likes        gross                           genres  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                 40000.0  309404152.0         Action|Adventure|Fantasy   
2                 11000.0  200074175.0        Action|Adventure|Thriller   
3                 27000.0  448130642.0                  Action|Thriller   
5                   640.0   73058679.0          Action|Adventure|Sci-Fi   

      actor_1_name                                movie_title  \
0      CCH Pounder                                    Avatar    
1      Johnny Depp  Pirates of the Caribbean: At World's End    
2  Christoph Waltz                                   Spectre    
3        Tom Hardy                     The Dark Knight Rises    
5     Daryl Sabara                               John Carter    

   num_voted_users  cast_total_facebook_likes          actor_3_name  \
0           886204                       4834             Wes Studi   
1           471220                      48350        Jack Davenport   
2           275868                      11700      Stephanie Sigman   
3          1144337                     106759  Joseph Gordon-Levitt   
5           212204                       1873          Polly Walker   

   facenumber_in_poster                                      plot_keywords  \
0                   0.0             avatar|future|marine|native|paraplegic   
1                   0.0  goddess|marriage ceremony|marriage proposal|pi...   
2                   1.0                bomb|espionage|sequel|spy|terrorist   
3                   0.0  deception|imprisonment|lawlessness|police offi...   
5                   1.0  alien|american civil war|male nipple|mars|prin...   

                                     movie_imdb_link  num_user_for_reviews  \
0  http://www.imdb.com/title/tt0499549/?ref_=fn_t...                3054.0   
1  http://www.imdb.com/title/tt0449088/?ref_=fn_t...                1238.0   
2  http://www.imdb.com/title/tt2379713/?ref_=fn_t...                 994.0   
3  http://www.imdb.com/title/tt1345836/?ref_=fn_t...                2701.0   
5  http://www.imdb.com/title/tt0401729/?ref_=fn_t...                 738.0   

  language country content_rating       budget  title_year  \
0  English     USA          PG-13  237000000.0      2009.0   
1  English     USA          PG-13  300000000.0      2007.0   
2  English      UK          PG-13  245000000.0      2015.0   
3  English     USA          PG-13  250000000.0      2012.0   
5  English     USA          PG-13  263700000.0      2012.0   

   actor_2_facebook_likes  imdb_score  aspect_ratio  movie_facebook_likes  
0                   936.0         7.9          1.78                 33000  
1                  5000.0         7.1          2.35                     0  
2                   393.0         6.8          2.35                 85000  
3                 23000.0         8.5          2.35                164000  
5                   632.0         6.6          2.35                 24000

In [9]:
categorical_features = ["color", "director_name", "actor_1_name", "actor_2_name", "actor_3_name", 
                        "language", "country", "content_rating"]

In [10]:
n_items = len(df)

In [11]:
#other szűrése a megfelelő kategóriánál
for feat in categorical_features:
    print("A %s feldolgozása. Egyedi mezők száma: %d" % (feat, df[feat].nunique()))
    if df[feat].nunique() < 50:
        print(df.groupby(feat).count().iloc[:,0])
        for feat_value in df[feat].unique():
            if(len(df[df[feat] == feat_value]) / n_items <= 0.02):
                print("A %s kategória hozzáadása az OTHER kategóriához." % feat_value)
                df[feat] = df[feat].apply(lambda x: "OTHER" if x == feat_value else x, 1)

A color feldolgozása. Egyedi mezők száma: 2
color
 Black and White     124
Color               3632
Name: director_name, dtype: int64
A director_name feldolgozása. Egyedi mezők száma: 1659
A actor_1_name feldolgozása. Egyedi mezők száma: 1428
A actor_2_name feldolgozása. Egyedi mezők száma: 2188
A actor_3_name feldolgozása. Egyedi mezők száma: 2587
A language feldolgozása. Egyedi mezők száma: 34
language
Aboriginal       2
Arabic           1
Aramaic          1
Bosnian          1
Cantonese        7
Czech            1
Danish           3
Dari             2
Dutch            3
English       3598
Filipino         1
French          34
German          10
Hebrew           1
Hindi            5
Hungarian        1
Indonesian       2
Italian          7
Japanese        10
Kazakh           1
Korean           5
Mandarin        15
Maya             1
Mongolian        1
None             1
Norwegian        4
Persian          3
Portuguese       5
Romanian         1
Russian          1
Spanish         23
Tha

In [12]:
#one-hot vector felbontás
df = pd.get_dummies(df, columns = ["color", "language", "country", "content_rating"])

In [13]:
df.head()

director_name  num_critic_for_reviews  duration  \
0      James Cameron                   723.0     178.0   
1     Gore Verbinski                   302.0     169.0   
2         Sam Mendes                   602.0     148.0   
3  Christopher Nolan                   813.0     164.0   
5     Andrew Stanton                   462.0     132.0   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
5                    475.0                   530.0   Samantha Morton   

   actor_1_facebook_likes        gross                           genres  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                 40000.0  309404152.0         Action|Adventure|Fantasy   
2                 11000.0  200074175.0        Action|Adventure|Thriller   
3                 27000.0  448130642.0                  Action|Thriller   
5                   640.0   73058679.0          Action|Adventure|Sci-Fi   

      actor_1_name                                movie_title  \
0      CCH Pounder                                    Avatar    
1      Johnny Depp  Pirates of the Caribbean: At World's End    
2  Christoph Waltz                                   Spectre    
3        Tom Hardy                     The Dark Knight Rises    
5     Daryl Sabara                               John Carter    

   num_voted_users  cast_total_facebook_likes          actor_3_name  \
0           886204                       4834             Wes Studi   
1           471220                      48350        Jack Davenport   
2           275868                      11700      Stephanie Sigman   
3          1144337                     106759  Joseph Gordon-Levitt   
5           212204                       1873          Polly Walker   

   facenumber_in_poster                                      plot_keywords  \
0                   0.0             avatar|future|marine|native|paraplegic   
1                   0.0  goddess|marriage ceremony|marriage proposal|pi...   
2                   1.0                bomb|espionage|sequel|spy|terrorist   
3                   0.0  deception|imprisonment|lawlessness|police offi...   
5                   1.0  alien|american civil war|male nipple|mars|prin...   

                                     movie_imdb_link  num_user_for_reviews  \
0  http://www.imdb.com/title/tt0499549/?ref_=fn_t...                3054.0   
1  http://www.imdb.com/title/tt0449088/?ref_=fn_t...                1238.0   
2  http://www.imdb.com/title/tt2379713/?ref_=fn_t...                 994.0   
3  http://www.imdb.com/title/tt1345836/?ref_=fn_t...                2701.0   
5  http://www.imdb.com/title/tt0401729/?ref_=fn_t...                 738.0   

        budget  title_year  actor_2_facebook_likes  imdb_score  aspect_ratio  \
0  237000000.0      2009.0                   936.0         7.9          1.78   
1  300000000.0      2007.0                  5000.0         7.1          2.35   
2  245000000.0      2015.0                   393.0         6.8          2.35   
3  250000000.0      2012.0                 23000.0         8.5          2.35   
5  263700000.0      2012.0                   632.0         6.6          2.35   

   movie_facebook_likes  color_ Black and White  color_Color  \
0                 33000                       0            1   
1                     0                       0            1   
2                 85000                       0            1   
3                164000                       0            1   
5                 24000                       0            1   

   language_English  language_OTHER  country_France  country_Germany  \
0                 1               0               0                0   
1       

In [15]:
x = df.loc[:,df.columns != "imdb_score"].values
y = df["imdb_score"]

In [16]:
df.describe()

num_critic_for_reviews     duration  director_facebook_likes  \
count             3756.000000  3756.000000              3756.000000   
mean               167.378328   110.257987               807.336528   
std                123.452040    22.646717              3068.171683   
min                  2.000000    37.000000                 0.000000   
25%                 77.000000    96.000000                11.000000   
50%                138.500000   106.000000                64.000000   
75%                224.000000   120.000000               235.000000   
max                813.000000   330.000000             23000.000000   

       actor_3_facebook_likes  actor_1_facebook_likes         gross  \
count             3756.000000             3756.000000  3.756000e+03   
mean               771.279553             7751.338658  5.261282e+07   
std               1894.249869            15519.339621  7.031787e+07   
min                  0.000000                0.000000  1.620000e+02   
25%                194.000000              745.000000  8.270233e+06   
50%                436.000000             1000.000000  3.009311e+07   
75%                691.000000            13000.000000  6.688194e+07   
max              23000.000000           640000.000000  7.605058e+08   

       num_voted_users  cast_total_facebook_likes  facenumber_in_poster  \
count     3.756000e+03                3756.000000           3756.000000   
mean      1.058267e+05               11527.101970              1.377263   
std       1.520354e+05               19122.176905              2.041541   
min       9.100000e+01                   0.000000              0.000000   
25%       1.966700e+04                1919.750000              0.000000   
50%       5.397350e+04                4059.500000              1.000000   
75%       1.286020e+05               16240.000000              2.000000   
max       1.689764e+06              656730.000000             43.000000   

       num_user_for_reviews        budget   title_year  \
count           3756.000000  3.756000e+03  3756.000000   
mean             336.843184  4.623685e+07  2002.976571   
std              411.227368  2.260103e+08     9.888108   
min                4.000000  2.180000e+02  1927.000000   
25%              110.000000  1.000000e+07  1999.000000   
50%              210.000000  2.500000e+07  2004.000000   
75%              398.250000  5.000000e+07  2010.000000   
max             5060.000000  1.221550e+10  2016.000000   

       actor_2_facebook_likes   imdb_score  aspect_ratio  \
count             3756.000000  3756.000000   3756.000000   
mean              2021.775825     6.465282      2.111014   
std               4544.908236     1.056247      0.353068   
min                  0.000000     1.600000      1.180000   
25%                384.750000     5.900000      1.850000   
50%                685.500000     6.600000      2.350000   
75%                976.000000     7.200000      2.350000   
max             137000.000000     9.300000     16.000000   

       movie_facebook_likes  color_ Black and White  color_Color  \
count           3756.000000             3756.000000  3756.000000   
mean            9353.829340                0.033014     0.966986   
std            21462.889123                0.178696     0.178696   
min                0.000000                0.000000     0.000000   
25%                0.000000                0.000000     1.000000   
50%              227.000000                0.000000     1.000000   
75%            11000.000000                0.000000     1.000000   
max           349000.000000                1.000000     1.000000   

       language_English  language_OTHER  country_France  country_Germany  \
count       3756.000000     3756.000000     3756.000000      3756.000000   
mean           0.957934        0.042066        0.026890         0.021299   
std            0.200767        0.200767        0.161784         0.144399   
min            0.000000        0.000000        0.000000         0.0000

In [17]:
#innentől más feladat

In [18]:
import numpy as np

In [23]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [22]:
b = np.array([(1.5,2.,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.empty((2,3)) #memóriaszemét

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [29]:
np.linspace(0,2,9) #számsor honnan, meddig, hány elem

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
np.arange(10) #számsor honnan, meddig(10), lépésköz,

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.eye(100) #egységmátrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [35]:
a

array([20, 30, 40, 50])

In [36]:
b

array([0, 1, 2, 3])

In [37]:
c = a-b
c

array([20, 29, 38, 47])

In [38]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [39]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [40]:
a<35

array([ True,  True, False, False])

In [41]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

In [42]:
A*B #elemenként

array([[2, 0],
       [0, 4]])

In [43]:
np.dot(A,B) #mátrix szorzás

array([[5, 4],
       [3, 4]])

In [44]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [46]:
A *=2
A

array([[4, 4],
       [0, 4]])

In [47]:
np.random.seed(42) #ugyanazzal a számmal ugyanazt a véletlent kapjuk (reprodukálható)

In [48]:
print(np.random.rand(2,3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


In [49]:
print(np.random.rand(2,3))

[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]


In [52]:
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
b[:,0]

array([ 0,  5, 10, 15])

In [55]:
b[-2,0]

10

In [56]:
b[::-1,:]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [58]:
a = np.floor(10*np.random.random((3,4)))

In [59]:
a

array([[8., 2., 1., 1.],
       [3., 5., 4., 2.],
       [6., 1., 2., 3.]])

In [60]:
a.T

array([[8., 3., 6.],
       [2., 5., 1.],
       [1., 4., 2.],
       [1., 2., 3.]])

In [61]:
a.reshape(3,-1) #kitalálja hány oszlop kell

array([[8., 2., 1., 1.],
       [3., 5., 4., 2.],
       [6., 1., 2., 3.]])

In [64]:
c = a
np.concatenate((a,c)) #sorok mentén konkatenál

array([[8., 2., 1., 1.],
       [3., 5., 4., 2.],
       [6., 1., 2., 3.],
       [8., 2., 1., 1.],
       [3., 5., 4., 2.],
       [6., 1., 2., 3.]])

In [65]:
d = a #referencia, shallow copy

In [66]:
print(a)
print(d)

[[8. 2. 1. 1.]
 [3. 5. 4. 2.]
 [6. 1. 2. 3.]]
[[8. 2. 1. 1.]
 [3. 5. 4. 2.]
 [6. 1. 2. 3.]]


In [67]:
a *=2

In [68]:
print(a)
print(d)

[[16.  4.  2.  2.]
 [ 6. 10.  8.  4.]
 [12.  2.  4.  6.]]
[[16.  4.  2.  2.]
 [ 6. 10.  8.  4.]
 [12.  2.  4.  6.]]


In [69]:
d is a

True

In [71]:
c = a.view()

In [72]:
c is a

False

In [73]:
r = a.copy() #deep copy, érték szerint

In [74]:
r is a

False

In [75]:
a /= 2

In [76]:
print(a)
print(r)

[[8. 2. 1. 1.]
 [3. 5. 4. 2.]
 [6. 1. 2. 3.]]
[[16.  4.  2.  2.]
 [ 6. 10.  8.  4.]
 [12.  2.  4.  6.]]


In [77]:
#garbage collector
import gc
gc.collect()

513